# allows SpaciousLib collects your server's information
stats: true
# enables the development mode
dev_mode: false
# should SpaciousLib renew skins automatically?
auto_renew_skin: false
# the duration between cache-renewing times
placeholder_cache_duration: 15
# uses asynchronous tasks for cached placeholders
placeholder_cache_async: true
# this is a list of proxies. They can be used for download skins from Mojang's server
# format: <address>:<port>
proxies:
- 194.126.183.141:53281
- 177.204.85.203:80
- 80.211.189.165:3128
- 147.135.210.114:54566
- 124.158.4.3:8080
- 192.116.142.153:8080
- 185.85.21.6:53281
- 185.93.3.123:8080
- 113.161.173.10:3128
- 5.197.183.222:8080
- 152.231.81.122:53281
- 94.130.14.146:31288

# ==================================
# pls don't change this
config_version: 2