name: SpaciousLib
version: 1.4.6
main: org.anhcraft.spaciouslib.SpaciousLib
authors: [anhcraft, inventivetalent]
description: A library has necessary utilities for all plugins
website: https://anhcraft.org/