# allows SpaciousLib collects your server's information
stats: true
# enables the development mode
dev_mode: false
# should SpaciousLib renew skins automatically?
auto_renew_skin: false
# the duration between cache-renewing times
placeholder_cache_duration: 15
# uses asynchronous tasks for cached placeholders
placeholder_cache_async: true

# ==================================
# pls don't change this
config_version: 1