name: SpaciousLib
version: 1.6.4
main: org.anhcraft.spaciouslib.SpaciousLib
loadbefore: [Vault,ProtocolLib]
authors: [anhcraft]
softdepend: [Vault,ProtocolLib]
description: A useful library for your Spigot/Bungeecord plugins and Java programs
website: https://anhcraft.org/
api-version: 1.13