name: SpaciousLib
version: 1.5.3
main: org.anhcraft.spaciouslib.SpaciousLib
loadbefore: [Vault]
authors: [anhcraft]
softdepend: [Vault]
description: A useful library for your Spigot plugins and Java programs
website: https://anhcraft.org/