name: SpaciousLib
version: 1.5.1
main: org.anhcraft.spaciouslib.SpaciousLib
authors: [anhcraft]
description: A useful library for your Spigot, Glowstone plugins and Java programs
website: https://anhcraft.org/